version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
#    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    - ./nginx.conf:/etc/nginx/nginx.conf
#    - ./static:/file_api/static
    ports:
    - "8080:80"

  web:
    build: .
    hostname: web
    ports:
    - "9393"
